Progress bar now showing progress! Calibrated for creating app with/without custom icon and with internal/external engine. Not yet calibrated for updating app with custom icon.

diff --git a/app/src/update/UpdateExec b/app/src/update/UpdateExec
--- a/app/src/update/UpdateExec
+++ b/app/src/update/UpdateExec
@@ -26,16 +26,47 @@
 updateVersion='EPIVERSION'
 
 
-# SUBAPP SETTINGS
+# PROGRESS BAR SETUP
 
-# don't write anything to stderr
-logNoStderr=1
+# kill parent app on abort
+killParentOnAbort=1
 
-# on abort, send ABRT signal to parent app
-killParentOnAbort=ABRT
+# step calibration
+stepStart=0
+step01=246
+step02=338
+step03=224
+step04=604
+step05=738
+step06=936
+step07=1179
+step08=936
+stepIconA1=659
+stepIconA2=10514
+stepIconA3=1164
+step09=672
+step10=524
+step11=432
+stepIEng1=835
+stepIEng2=863
+stepIEng3=860
+stepIEng4=28310
+step12=339
 
-# on Cancel button, send TERM signal to parent app
-trap handlecancel TERM
+# set up progress total based on what we're doing in this update
+progressTotal=$(( $stepStart + $step01 + $step02 + $step03 + $step04 + $step05 + $step06 + $step07 + $step08 + $step09 + $step10 + $step11 + $step12 ))
+ 
+# custom icon progress
+if [[ "$SSBCustomIcon" = Yes ]] ; then
+    if [[ "$epiIconSource" ]] ; then
+        progressTotal=$(( $progressTotal + $stepIconA1 + $stepIconA2 + $stepIconA3 ))
+    else
+        progressTotal=$(( $progressTotal + $stepIconB1 + $stepIconB2 + $stepIconB3 + $stepIconB4 + $stepIconB5 + $stepIconB6 ))
+    fi
+fi
+
+# internal engine progress
+[[ "${SSBEngineType%%|*}" = internal ]] && progressTotal=$(( $progressTotal + $stepIEng1 + $stepIEng2 + $stepIEng3 + $stepIEng4 ))
 
 
 # PATH TO THIS APP'S PARENT EPICHROME APP BUNDLE
@@ -50,22 +81,25 @@ updateContentsTmp=
 updateBackupFile=
 
 
-# BOOTSTRAP MY VERSION OF CORE.SH & LAUNCH.SH
+# BOOTSTRAP MY VERSION OF CORE.SH, PROGRESS.SH, LAUNCH.SH
 
-#if [[ "$updateVersion" != "$coreVersion" ]] ; then  $$$ ALWAYS RELOAD EVERYTHING??
-    if ! source "$updateEpichromeRuntime/Contents/Resources/Scripts/core.sh" \
-            'coreDoInit=1' 'logIDExt=Update' "$@" ; then
-        ok= ; errmsg="Unable to load core $updateVersion."
-        abort
-        echo "$errmsg" 1>&2 ; exit 1  # in case abort is not set
-    fi
-#fi
+if ! source "$updateEpichromeRuntime/Contents/Resources/Scripts/core.sh" \
+'coreDoInit=1' 'logIDExt=Update' "$@" ; then
+    ok= ; errmsg="Unable to load core $updateVersion."
+    abort
+    echo "$errmsg" 1>&2 ; exit 1  # in case abort is not set
+fi
+[[ "$ok" ]] || abort
 
-if [[ "$ok" ]] ; then
-    if ! source "$updateEpichromeRuntime/Contents/Resources/Scripts/launch.sh" ; then
-        ok= ; errmsg="Unable to load launch.sh $updateVersion."
-        abort
-    fi
+progressAction="$updateAppMessage"
+if ! source "$updateEpichromeRuntime/Contents/Resources/Scripts/progress.sh" ; then
+    ok= ; errmsg="Unable to load progress.sh $updateVersion."
+    abort
+fi
+
+if ! source "$updateEpichromeRuntime/Contents/Resources/Scripts/launch.sh" ; then
+    ok= ; errmsg="Unable to load launch.sh $updateVersion."
+    abort
 fi
 
 
@@ -83,24 +117,13 @@ function escapehtml {  # ( str )
     ok=1 ; errmsg=
 }
 
-# MYABORT: abort wrapper to distinguish from a canceled update
-updateComplete=
-function myabort {
-    updateComplete=1
-    abort "$@"
-}
 
-
-# HANDLECANCEL: handle a cancel signal
-function handlecancel {
-    errlog FATAL "Operation canceled."
-    killParentOnAbort=TERM
-    cleanexit 1
-}
-
-
-# CLEANUP: clean up from an incomplete update
+# CLEANUP: clean up any incomplete update prior to exit
 function cleanup {
+    
+    # set final progress message
+    echo "$progressFinalMessage"
+    
     local cleaned=1
 
     debuglog "Cleaning up..."
@@ -122,7 +145,8 @@ function cleanup {
 
 # --- MAIN BODY ---
 
-echo "$updateAppMessage..."
+# $$$
+progress 'stepStart'  # $$$
 
 # $$$
 #sleep 30
@@ -147,12 +171,14 @@ fi
 # get current info for the engine
 getbrowserinfo SSBEngineSourceInfo
 
+progress 'step01'  # $$$
 
 # LOAD FILTER.SH
 
 safesource "$updateEpichromeRuntime/Contents/Resources/Scripts/filter.sh"
 [[ "$ok" ]] || abort
 
+progress 'step02'  # $$$
 
 # SET APP BUNDLE ID
 
@@ -204,6 +230,8 @@ if [[ "$epiAction" != 'build' ]] ; then
     fi
 fi
 
+progress 'step03'  # $$$
+
 
 # SET APP VERSION
 
@@ -221,10 +249,14 @@ try /bin/cp -PR "$updateEpichromeRuntime/Contents" "$updateContentsTmp" \
         'Unable to populate app bundle.'
 [[ "$ok" ]] || abort
 
+progress 'step04'  # $$$
+
 # copy executable into place
 safecopy "$updateEpichromeRuntime/Exec/Epichrome" \
         "$updateContentsTmp/MacOS/Epichrome" \
         'app executable.'
+
+progress 'step05'  # $$$
 
 
 # FILTER APP INFO.PLIST INTO PLACE
@@ -243,6 +275,8 @@ filterplist "$updateEpichromeRuntime/Filter/Info.plist" \
         "$updateContentsTmp/Info.plist" \
         "app Info.plist" \
         "${filterCommands[@]}"
+
+progress 'step06'  # $$$
 
 
 # FILTER APPEXEC & MAIN.SH INTO PLACE
@@ -265,6 +299,8 @@ filterfile "$updateEpichromeRuntime/Filter/AppExec" \
         'app bootstrap script' \
         APPID "$(formatscalar "$SSBIdentifier")"
     
+progress 'step07'  # $$$
+
 # filter main.sh & make executable
 iMainScript="$resourcesTmp/Scripts/main.sh"
 filterfile "$updateEpichromeRuntime/Filter/main.sh" \
@@ -281,8 +317,9 @@ filterfile "$updateEpichromeRuntime/Filter/main.sh" \
         APPCOMMANDLINE "$(formatarray "${SSBCommandLine[@]}")" \
         APPEDITED "$(formatscalar "$editedTimestamp")"
 try /bin/chmod 755 "$iMainScript" 'Unable to set permissions for main app script.'
-
 [[ "$ok" ]] || abort
+
+progress '!step08'  # $$$
 
 
 # COPY OR CREATE CUSTOM APP ICONS
@@ -300,6 +337,8 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
         try '!1' /usr/bin/sips --getProperty format "$epiIconSource" \
                 "Unable to parse icon source file."
         [[ "$ok" ]] || abort
+        
+        progress '!stepIconA1'  # $$$
         
         # find makeicon.sh
         makeIconScript="$updateEpichromeResources/Scripts/makeicon.sh"
@@ -320,6 +359,8 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
         # run script to convert image into an ICNS
         makeIconErr=
         try 'makeIconErr&=' "$makeIconScript" -f -o "$resourcesTmp/$CFBundleIconFile" "${docArgs[@]}" ''
+        
+        progress 'stepIconA2'  # $$$
         
         # handle errors
         if [[ ! "$ok" ]] ; then
@@ -342,6 +383,8 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
         # error is nonfatal, we'll just use the default from boilerplate
         if [[ ! "$ok" ]] ; then ok=1 ; errmsg= ; fi
         
+        progress 'stepIconA3'  # $$$
+        
     else
         
         
@@ -352,8 +395,14 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
         iconSourcePath="$updateAppPath/Contents/Resources"
         safecopy "$iconSourcePath/$CFBundleIconFile" \
                 "$resourcesTmp/$CFBundleIconFile" "app icon"
+        
+        progress 'stepIconB1'  # $$$
+
         safecopy "$iconSourcePath/$CFBundleTypeIconFile" \
                 "$resourcesTmp/$CFBundleTypeIconFile" "document icon"
+        
+        progress 'stepIconB2'  # $$$
+        
         [[ "$ok" ]] || abort
         
         
@@ -377,6 +426,8 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
                     -o "$tempIconset" \
                     "$iconSourcePath/$CFBundleIconFile" \
                     'Unable to convert app icon to iconset.'
+            
+            progress 'stepIconB3'  # $$$
             
             if [[ "$ok" ]] ; then
                 
@@ -414,12 +465,16 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
             debuglog 'Found existing icon image for welcome page.'
         fi
         
+        progress 'stepIconB4'  # $$$
+        
         # copy welcome icon
         if [[ "$welcomeIconSourcePath" ]] ; then
             safecopy "$welcomeIconSourcePath" \
                     "$updateContentsTmp/$welcomeIconBase" \
                     'Unable to add app icon to welcome page.'
         fi
+        
+        progress 'stepIconB5'  # $$$
         
         # get rid of any temp iconset we created
         [[ "$tempIconset" && -e "$tempIconset" ]] && \
@@ -428,8 +483,12 @@ if [[ "$SSBCustomIcon" = Yes ]] ; then
 
         # welcome page icon error is nonfatal, just log it
         if [[ ! "$ok" ]] ; then ok=1 ; errmsg= ; fi
+        
+        progress 'stepIconB6'  # $$$
     fi
+
 fi
+
 
 
 # FILTER WELCOME PAGE INTO PLACE
@@ -439,6 +498,8 @@ filterfile "$updateEpichromeRuntime/Filter/$appWelcomePage" \
         'welcome page' \
         APPBUNDLENAME "$(escapehtml "$CFBundleName")" \
         APPDISPLAYNAME "$(escapehtml "$CFBundleDisplayName")"
+
+progress 'step09'  # $$$
 
 
 # SELECT MASTER PREFS
@@ -454,14 +515,18 @@ safecopy "$updateEpichromeRuntime/Filter/Prefs/prefs${nourl}_${engineID//./_}.js
         'Unable to create app master prefs.'
 
 
+progress 'step10'  # $$$
+
+
 # FILTER PROFILE BOOKMARKS FILE INTO PLACE
 
 filterfile "$updateEpichromeRuntime/Filter/$appBookmarksFile" \
         "$updateContentsTmp/$appBookmarksPath" \
         'bookmarks template' \
         APPBUNDLENAME "$(escapejson "$CFBundleName")"
-
 [[ "$ok" ]] || abort
+
+progress 'step11'  # $$$
 
 
 # POPULATE INTERNAL ENGINE DIRECTORY
@@ -476,10 +541,14 @@ if [[ "${SSBEngineType%%|*}" = internal ]] ; then
             "$updateEnginePath" \
             'Unable to populate app engine payload.'
     
+    progress 'stepIEng1'  # $$$
+    
     # copy payload executable into place
     safecopy "$updateEpichromeRuntime/Engine/Exec/${SSBEngineSourceInfo[$iExecutable]}" \
             "$updateEnginePath/MacOS/${SSBEngineSourceInfo[$iExecutable]}" \
             'app engine payload executable'
+    
+    progress 'stepIEng2'  # $$$
     
     # filter payload Info.plist into place
     filterplist "$updateEpichromeRuntime/Engine/Filter/Info.plist" \
@@ -489,9 +558,13 @@ if [[ "${SSBEngineType%%|*}" = internal ]] ; then
             "Set :CFBundleName $(escape "$CFBundleName" "\"'")" \
             "Set :CFBundleIdentifier $myAppBundleID"
     
+    progress 'stepIEng3'  # $$$
+    
     # filter localization strings in place
     filterlproj "$updateEnginePath/Resources" 'app engine' \
-            "${SSBEngineSourceInfo[$iName]}"
+            "${SSBEngineSourceInfo[$iName]}" 'stepIEng4'
+
+    #progress 'stepIEng4'  # CALIBRATION ONLY
 fi
 
 
@@ -515,6 +588,8 @@ else
     abort
 fi
 
+progress 'step12'  # $$$
+
 
 # CREATE FAILSAFE BACKUP OF APP
 
@@ -537,5 +612,9 @@ if [[ "$ok" ]] ; then
 else
     ok=1 ; errmsg=
 fi
+
+progress 'end'  # $$$
+
+progressFinalMessage='Operation complete.'
 
 cleanexit
