Started laying groundwork for Brave engine by generalizing Makefile engine code. Put back in Google APIs for Chromium engine after the ungoogled version sucked.

diff --git a/app/Makefile b/app/Makefile
--- a/app/Makefile
+++ b/app/Makefile
@@ -60,20 +60,42 @@ MIN_OS:="$$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' '$(APP)/C
 BETA:=$(shell if [[ '$(VERSION)' =~ b ]] ; then echo _beta ; else echo '' ; fi)
 
 
-# CHROMIUM VERSION
+# CHROMIUM ENGINE
 # (Using Marmaduke build with Google APIs and Widevine from https://chromium.woolyss.com/)
 
-CHROMIUM:=$(shell ls Chromium/Chromium.*.sync.app.* 2> /dev/null | sort -r | head -n 1)
+CHROMIUM:=$(shell ls Engine/Chromium* 2> /dev/null | sort -r | head -n 1)
 ifeq ($(CHROMIUM),)
 $(error Unable to find Chromium archive)
 endif
 ifneq ($(suffix $(CHROMIUM)),.tgz)
 ifneq ($(suffix $(CHROMIUM)),.zip)
-$(error Unrecognized file in Chromium directory: $(CHROMIUM))
+$(error Unrecognized file in Engine directory: $(CHROMIUM))
 endif
 CHROMIUM:=$(CHROMIUM:.zip=.tgz)
 endif
-CHROMIUM_VERSION:=$(patsubst Chromium/Chromium.%.sync.app.tgz,%,$(CHROMIUM))
+CHROMIUM_VERSION:=$(shell if [[ '$(CHROMIUM)' =~ [0-9][0-9.]*[0-9] ]] ; then \
+				echo "$${BASH_REMATCH[0]}" ; else echo ERROR ; fi)
+ifeq ($(CHROMIUM_VERSION),ERROR)
+$(error Unable to retrieve Chromium version from $(CHROMIUM))
+endif
+
+# BRAVE ENGINE
+
+BRAVE:=$(shell ls Engine/Brave* 2> /dev/null | sort -r | head -n 1)
+ifeq ($(BRAVE),)
+$(error Unable to find Brave archive)
+endif
+ifneq ($(suffix $(BRAVE)),.tgz)
+ifneq ($(suffix $(BRAVE)),.dmg)
+$(error Unrecognized file in Engine directory: $(BRAVE))
+endif
+BRAVE:=$(BRAVE:.dmg=.tgz)
+endif
+BRAVE_VERSION:=$(shell if [[ '$(BRAVE)' =~ [0-9][0-9.]*[0-9] ]] ; then \
+				echo "$${BASH_REMATCH[0]}" ; else echo ERROR ; fi)
+ifeq ($(BRAVE_VERSION),ERROR)
+$(error Unable to retrieve Brave version from $(CHROMIUM))
+endif
 
 
 # NOTARIZE INFO
@@ -110,12 +132,12 @@ APP_RNTM_HLPR_CT:=$(APP_RNTM_HLPR)/Contents
 
 .DELETE_ON_ERROR:
 
-.PHONY: internal install clean clean-all
+.PHONY: engine runtime internal install clean clean-all
 
 .PRECIOUS: $(PRECIOUS_INTERMEDIATES)
 
 INTERMEDIATES:=\
-	build/engine \
+	build/engine/Chromium \
 	build/fake.icns \
 	build/fake.sh \
 	build/Chromium.app \
@@ -133,7 +155,7 @@ PRECIOUS_INTERMEDIATES:=\
 	build/resources/license.rtf \
 	build/resources/readme.rtf
 
-.INTERMEDIATE: main runtime engine $(INTERMEDIATES) $(PRECIOUS_INTERMEDIATES)
+.INTERMEDIATE: main $(INTERMEDIATES) $(PRECIOUS_INTERMEDIATES)
 
 
 # INTERNAL BUILD (DEFAULT TARGET)
@@ -148,6 +170,7 @@ internal: $(APP)
 clean:
 	rm -rf Epichrome/* epichrome-*.pkg
 	rm -rf build/main* build/runtime* $(INTERMEDIATES)
+	@hdiutil detach build/brave 2> /dev/null || true
 
 clean-package:
 	rm -f epichrome-*.pkg
@@ -526,9 +549,10 @@ build/img/icon128$(BETA).png: ../images/icons/app$(BETA).png
 
 # CODESIGNED CHROMIUM
 
-build/engine: $(CHROMIUM)
-	@rm -rf build/engine
-	tar xzvf $(CHROMIUM) --cd build
+build/engine/Chromium: $(CHROMIUM)
+	@rm -rf build/engine/Chromium
+	@mkdir -p build/engine
+	tar xzvf $(CHROMIUM) --cd build/engine
 
 CHROMIUM_FRAMEWORK:=build/chromium/Contents/Frameworks/Chromium Framework.framework
 # find Chromium.app -exec bash -c 'codesign --verify --deep --strict "{}" 2> /dev/null && codesign --verify --deep --strict --verbose=2 "{}"' ';'
@@ -536,7 +560,7 @@ $(CHROMIUM): $(CHROMIUM:.tgz=.zip)
 	@mkdir -p build/chromium
 	tar xzvf '$<' --cd build/chromium --strip-components 1
 	codesign --remove-signature -vv build/chromium
-	rmdir build/chromium/Contents/_CodeSignature
+	rm -rf build/chromium/Contents/_CodeSignature
 # codesign --remove-signature -vv \
 # 	'$(CHROMIUM_FRAMEWORK)' \
 # 	'$(CHROMIUM_FRAMEWORK)/Versions/Current/XPCServices/AlertNotificationService.xpc' \
@@ -550,11 +574,33 @@ $(CHROMIUM): $(CHROMIUM:.tgz=.zip)
 		'$(CHROMIUM_FRAMEWORK)/Versions/Current/XPCServices/AlertNotificationService.xpc' \
 		'$(CHROMIUM_FRAMEWORK)'
 #		'build/chromium'
-	@rm -rf build/engine
-	mv build/chromium/Contents build/engine
+	@rm -rf build/engine/Chromium
+	@mkdir -p build/engine
+	mv build/chromium/Contents build/engine/Chromium
 	rmdir build/chromium
-	tar czvf '$@' --cd build engine
-	@touch build/engine
+	tar czvf '$@' --cd build/engine Chromium
+	@touch build/engine/Chromium
+
+BRAVE_FRAMEWORK:=build/brave/Contents/Frameworks/Brave Browser Framework.framework
+$(BRAVE): $(BRAVE:.tgz=.dmg)
+	@rm -rf build/brave
+	hdiutil attach -nobrowse -mountpoint build/bravedmg '$<'
+	cp -PRv 'build/bravedmg/Brave Browser.app' build/brave
+	hdiutil detach build/bravedmg
+	codesign --remove-signature -vv build/brave
+	rmdir build/brave/Contents/_CodeSignature
+	@if [[ ! -d '$(BRAVE_FRAMEWORK)/Versions/Current/Frameworks/Sparkle.framework' ]] ; then \
+		echo '*** Unable to find Sparkle.framework' 1>&2 ; false ; fi
+	rm -rf '$(BRAVE_FRAMEWORK)/Versions/Current/Frameworks/Sparkle.framework'
+	xattr -cr build/brave
+	src/signmatch.sh '' \
+		'$(BRAVE_FRAMEWORK)'
+#		'build/brave'
+	@rm -rf build/braveengine
+	mv build/brave/Contents build/braveengine
+	rmdir build/brave
+#	tar czvf '$@' --cd build braveengine
+	@touch build/braveengine
 
 
 # ENGINE FILTER ELEMENTS
@@ -562,24 +608,24 @@ $(CHROMIUM): $(CHROMIUM:.tgz=.zip)
 $(APP_RNTM)/Engine/Filter/Info.plist $(APP_RNTM)/Engine/Payload $(APP_RNTM)/Engine/Link/Frameworks: \
 		$(CHROMIUM) src/version.sh engine
 
-engine: build/engine
-	@if [[ "$$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIconFile' build/engine/Info.plist)" != 'app.icns' ]] ; then \
-		echo '*** Chromium app icon name has changed.' 1>&2 ; false ; fi
+engine: build/engine/Chromium
+	@if [[ "$$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIconFile' build/engine/Chromium/Info.plist)" != 'app.icns' ]] ; then \
+		echo '*** Internal engine app icon name has changed.' 1>&2 ; false ; fi
 	/usr/libexec/PlistBuddy -c 'Set :CFBundleShortVersionString $(VERSION)' \
 				-c 'Delete :CFBundleDocumentTypes' \
 				-c 'Delete :CFBundleURLTypes' \
-				build/engine/Info.plist
+				build/engine/Chromium/Info.plist
 	@mkdir -p $(APP_RNTM)/Engine/Filter
-	mv -f build/engine/Info.plist $(APP_RNTM)/Engine/Filter/Info.plist
+	mv -f build/engine/Chromium/Info.plist $(APP_RNTM)/Engine/Filter/Info.plist
 	rm -rf $(APP_RNTM)/Engine/Link $(APP_RNTM)/Engine/Payload
 	mkdir -p $(APP_RNTM)/Engine/Link
-	mv build/engine/Frameworks $(APP_RNTM)/Engine/Link/Frameworks
+	mv build/engine/Chromium/Frameworks $(APP_RNTM)/Engine/Link/Frameworks
 	@touch $(APP_RNTM)/Engine/Link/Frameworks
-	rm -f build/engine/Resources/*.icns
-	openssl AES-128-CBC -k data -in 'build/engine/MacOS/Chromium' -out '$(APP_RNTM)/Engine/exec.dat'
-	rm build/engine/MacOS/Chromium
-	rmdir build/engine/MacOS
-	mv build/engine $(APP_RNTM)/Engine/Payload
+	rm -f build/engine/Chromium/Resources/*.icns
+	openssl AES-128-CBC -k data -in 'build/engine/Chromium/MacOS/Chromium' -out '$(APP_RNTM)/Engine/exec.dat'
+	rm build/engine/Chromium/MacOS/Chromium
+	rmdir build/engine/Chromium/MacOS
+	mv build/engine/Chromium $(APP_RNTM)/Engine/Payload
 	@touch $(APP_RNTM)/Engine/Payload
 
 $(APP_RNTM)/Engine/Filter/PlaceholderExec: src/PlaceholderExec src/version.sh
