Fixed bug in launch check that would cause an app to think it was already running if another app was running that began with the same ID. Added code to create a log if an app dies because another instance is running.

diff --git a/app/src/AppExec b/app/src/AppExec
--- a/app/src/AppExec
+++ b/app/src/AppExec
@@ -21,18 +21,48 @@
 #
 
 
+# CORE APP INFO
+
+# filled in by updateapp
+SSBIdentifier=APPID
+
+
 # ENSURE APP ISN'T ALREADY RUNNING (OR THIS IS A RELAUNCH), THEN FORK & TERMINATE
 
 # unique ID tag for this app in the process table
 idTag='--epichrome-id=APPID'
+idGrep="$idTag"'([^-a-z0-9_]|$)'
 
 if [[ "$1" = '--relaunch' ]] ; then
     # this is a relaunch, so don't check for the ID tag
     shift
 else
     # if ID tag is in process table, we're already running
-    if /usr/bin/pgrep -fiq -- "$idTag" ; then
-        exit 0
+    if /usr/bin/pgrep -fiq -- "$idGrep" ; then
+        
+        # LOG FAILED LAUNCH
+        
+        # load core script
+        myLogID=   # reset log ID
+        source "${BASH_SOURCE[0]%/script}/Scripts/core.sh" 'coreDoInit=1' || exit 1
+        [[ "$ok" ]] || abortreport
+        
+        # initialize log file
+        initlogfile
+        
+        # try to get PID of running app
+        runningPID=()
+        try 'runningPID=(n)' /usr/bin/pgrep -fi -- "$idGrep" \
+                'Unable to get PID of other app instance'
+        ok=1 ; errmsg=
+        
+        # log failed launch
+        errmsg='Cannot launch. Another instance of this app is already running'
+        [[ "${runningPID[0]}" ]] && errmsg+=" at PID ${runningPID[0]}"
+        errmsg+='.'
+        errlog FATAL "$errmsg"
+        
+        cleanexit
     fi
 fi
 
