Some large-scale architecture changes, including moving update functions into their own script file. Not currently working.

diff --git a/app/src/epichrome b/app/src/epichrome
--- a/app/src/epichrome
+++ b/app/src/epichrome
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 #  Epichrome: Run an Epichrome app
-#  Copyright (C) 2019  David Marmor
+#  Copyright (C) 2020  David Marmor
 #
 #  https://github.com/dmarmor/epichrome
 #
@@ -22,9 +22,10 @@
 #
 
 
-# DEBUG FLAG (CAN BE OVERRIDDEN BY RUNTIME.SH)
+# BUILD FLAGS (CAN BE OVERRIDDEN BY RUNTIME.SH)
 
 debug=
+logPreserve=
 
 
 # FUNCTION DEFINITIONS
@@ -369,6 +370,10 @@ while [[ "$#" -gt 0 ]] ; do
             debug=1
             ;;
 
+	--epichrome-preserve-logs)
+	    logPreserve=1
+	    ;;
+
 	[hH][tT][tT][pP]'://'*|[hH][tT][tT][pP][sS]'://'*|[fF][tT][pP]'://'*|[fF][iI][lL][eE]'://'*)
 	    # this should be sent to the open command
 	    argsURIs+=( "$1" )
@@ -384,17 +389,13 @@ while [[ "$#" -gt 0 ]] ; do
 done
 
 
-# BOOTSTRAP RUNTIME SCRIPT
+# BOOTSTRAP THIS APP'S RUNTIME SCRIPT
 
-# determine location of runtime script
-myPath=$(cd "$(dirname "$0")/../.."; pwd)
+source "${0%/*}/../Resources/Scripts/runtime.sh"
+[[ "$?" != 0 ]] && abort 'Unable to load runtime script.'
+
+# useful paths
 myContents="$myPath/Contents"
-[[ $? != 0 ]] && abort 'Unable to determine app path.' 1
-[[ "$myPath" =~ \.[aA][pP][pP]$ ]] || abort 'Unexpected app path.' 1
-
-# load main runtime functions
-source "${myContents}/Resources/Scripts/runtime.sh"
-[[ $? != 0 ]] && abort 'Unable to load runtime script.' 1
 
 # temporary logApp until we read config
 logApp="${myPath##*/}"
@@ -415,10 +416,12 @@ myProfileArg="--user-data-dir=$myProfilePath"
 
 # override runtime.sh debug log path & start fresh
 logApp="$CFBundleName"
-logPath="$myProfilePath/_epichrome/log.txt"
+logPath="$myProfilePath/_epichrome/epichrome_app_log.txt"
 stderrTempFile="$myProfilePath/_epichrome/stderr.txt"
-/bin/rm -f "$logPath"
 /bin/mkdir -p "$myProfilePath/_epichrome"
+
+# clear the old log, unless logPreserve is set
+clearlog
 
 # by default, use existing profile
 newprofile=
@@ -480,12 +483,10 @@ fi
 
 # CHECK FOR NEW VERSION OF EPICHROME AND UPDATE
 
-# get info on current Epichrome version
+# get info on latest Epichrome version
 epichromeinfo
-if [[ ! "$ok" ]] ; then
-    # fail silently, and we just won't check for updates
-    ok=1 ; errmsg=
-fi
+[[ "$ok" ]] || abort "$errmsg"
+epiVersion="${epiLatest[$e_version]}"
 
 if [[ "$(newversion "$SSBVersion" "$epiVersion")" ]] ; then
 
@@ -520,16 +521,34 @@ if [[ "$(newversion "$SSBVersion" "$epiVersion")" ]] ; then
 		Update)
 
 		    # read in the new runtime
-		    safesource "$epiContents/Resources/Runtime/Resources/Scripts/runtime.sh" "updated runtime script"
+		    safesource "$epiContents/Resources/Scripts/update.sh" "update script $epiVersion"
 
 		    # use new runtime to update the SSB (and relaunch)
 		    updateapp "$myPath"
-
-		    # relaunch after a delay
+		    
 		    if [[ "$ok" ]] ; then
+			
+			# SUCCESS -- relaunch after a delay
 			relaunch "$myPath" 1 &
 			disown -ar
 			exit 0
+
+		    else
+
+			# UPDATE FAILED -- reload my runtime
+			
+			# temporarily turn OK back on & reload old runtime
+			oldErrmsg="$errmsg" ; errmsg=
+			oldOK="$ok" ; ok=1
+			safesource "$myPath/Contents/Resources/Scripts/runtime.sh" "runtime script $SSBVersion"
+			[[ "$ok" ]] && ok="$oldOK"
+			
+			# update error message
+			if [[ "$oldErrmsg" && "$errmsg" ]] ; then
+			    errmsg="$oldErrmsg $errmsg"
+			elif [[ "$oldErrmsg" ]] ; then
+			    errmsg="$oldErrmsg"
+			fi
 		    fi
 		    ;;
 
@@ -566,25 +585,20 @@ if [[ "$ok" ]] ; then
 	# set next update for 7 days from now
 	SSBUpdateCheckDate=$(($curDate + (7 * 24 * 60 * 60)))
 
-	# if we haven't set a version to check against, use the current version
-	[[ "$SSBUpdateCheckVersion" ]] || SSBUpdateCheckVersion="$epiVersion"
+	# if we haven't set a version to check against, use the latest version
+	[[ "$SSBUpdateCheckVersion" ]] || SSBUpdateCheckVersion="${epiLatest[$e_version]}"
 
 	# check if there's a new version on Github
-	try 'updateResult=' checkepichromeversion "$myContents" "$SSBUpdateCheckVersion" 'Unable to check for a new version of Epichrome on Github.'
+	try 'updateResult=(n)' checkepichromeversion "$myContents" "$SSBUpdateCheckVersion" \
+	    'Unable to check for a new version of Epichrome on Github.'
 	if [[ ! "$ok" ]] ; then
 	    alert "Warning: $errmsg" 'Checking For Update' '|caution'
 	    ok=1
 	else
-
+	    
 	    # if there's an update available, display a dialog
-	    if [[ "$updateResult" ]] ; then
-		# set separator to newline
-		oldifs="$IFS"
-		IFS=$'\n'
-
-		# convert result into an array
-		updateResult=( $(echo "$updateResult") )
-
+	    if [[ "${updateResult[*]}" ]] ; then
+		
 		# display dialog
 		dialog doEpichromeUpdate \
 		   "A new version of Epichrome (${updateResult[0]}) is available on GitHub." \
@@ -687,6 +701,9 @@ else
 		newPayload=1
 	    fi
 	else
+
+	    # #$$$$ LINKED TO epiEngineRuntime thing, need range of compatible versions!!
+	    
 	    # get Epichrome Chromium payload manifest
 	    engineManifest="$(cd "$epiPayload" && (echo './Contents/Resources/app.icns' && echo './Contents/Resources/document.icns' && /usr/bin/find -L . -print) | /usr/bin/sed -E -e 's/InfoPlist\.strings.in/InfoPlist.strings/' -e 's/Info.plist.in/Info.plist.off/' | /usr/bin/sort)"
 	    if [[ "$?" != 0 ]] ; then
@@ -735,7 +752,11 @@ if [[ "$SSBEngineType" != "Google Chrome" ]] ; then
 
     # EPICHROME CHROMIUM ENGINE
 
-    # link to everything except Resources directory
+    if [[ ! "$epiCurrent" ]] ; then
+	### $$$$ MUST FIX THIS!!! NEED A RANGE OF COMPATIBLE VERSIONS
+	abort "Unable to find current version of Epichrome, which is needed to run with the Chromium engine."
+    fi
+    # link to everything except Resources directory  $$$ REPLACE epiEngineRuntime calls
     dirlist "$epiEngineRuntime" curdir 'Epichrome app engine' '^Resources$'
     linktree "$epiEngineRuntime" "$myEngineAppContents" \
 	     'Epichrome app engine' "${curdir[@]}"
@@ -1160,6 +1181,9 @@ getenginepid "$myEngineID" "$SSBEngineAppPath"
 
 if [[ "$enginePID" ]] ; then
 
+    # export debug & log options for cleanup daemon
+    export debug logPreserve
+    
     # PID found, so launch cleanup daemon
     try /usr/bin/open "$myContents/$appCleanup" --args "$SSBEngineType" "$enginePID" "$SSBEngineAppPath" "$logPath" "$stderrTempFile" \
 	'Unable to lauch cleanup helper. The app engine will not be properly cleaned up upon quitting.'
