Update system fully implemented for both Epichrome and apps.

diff --git a/app/src/epichrome b/app/src/epichrome
--- a/app/src/epichrome
+++ b/app/src/epichrome
@@ -44,7 +44,7 @@ function unsudo {
 
 # DIALOG -- display a dialog and return the button pressed
 function dialog {  # VAR MESSAGE TITLE ICON (if starts with | try app icon first) BUTTON1 BUTTON2 BUTTON3 (+ = default, - = cancel)
-    
+
     if [[ "$ok" ]] ; then
 
 	local var="$1" ; shift ; [[ "$var" ]] || var=var  # if not capturing, just save dialog text to this local
@@ -78,7 +78,8 @@ end tell"
 	local try_start=
 	local try_end=
 	local numbuttons=0
-	for button in "${@:1:3}" ; do
+	
+	for button in $@ ; do
 	    # increment button count
 	    numbuttons=$((${numbuttons} + 1))
 	    
@@ -98,7 +99,7 @@ end try"
 	    # add to button list
 	    buttonlist="$buttonlist, \"$button\""
 	done
-
+	
 	# if no buttons specified, make one default OK button
 	if [[ "$numbuttons" -eq 0 ]]; then
 	    numbuttons=1
@@ -109,7 +110,7 @@ end try"
 	
 	# close button list
 	buttonlist="{ ${buttonlist:2} }"
-	
+
 	# run the dialog
 	
 	try "${var}=" osascript -e "$icon_set
@@ -372,7 +373,7 @@ if [ "$SSBChromeVersion" != "$chromeVersion" ] ; then
 fi
 
 
-# CHECK FOR NEW VERSION OF MAKECHROMESSB AND UPDATE
+# CHECK FOR NEW VERSION OF EPICHROME AND UPDATE
 
 if [[ "$(newversion "$SSBVersion" "$mcssbVersion")" ]] ; then
 
@@ -425,6 +426,79 @@ if [[ "$(newversion "$SSBVersion" "$mcssbVersion")" ]] ; then
 	if [[ ! "$ok" ]] ; then
 	    alert "$errmsg Please try update again later." 'Unable to Update' '|caution'
 	    ok=1
+	fi
+    fi
+fi
+
+
+# CHECK FOR A NEW VERSION OF EPICHROME ON GITHUB
+
+try 'curDate=' /bin/date '+%s' 'Unable to get date for Epichrome update check.'
+if [[ "$ok" ]] ; then
+    
+    # check for updates if we've never run a check, or if the next check date is in the past
+    if [[ ( ! "$SSBUpdateCheckDate" ) || ( "$SSBUpdateCheckDate" -lt "$curDate" ) ]] ; then
+
+	# set next update for 7 days from now
+	SSBUpdateCheckDate=$(($curDate + (7 * 24 * 60 * 60)))
+	updateconfig=1
+	
+	# if we haven't set a version to check against, use the current version
+	[[ "$SSBUpdateCheckVersion" ]] || SSBUpdateCheckVersion="$mcssbVersion"
+
+	# check if there's a new version on Github
+	try 'updateResult=' checkmcssbversion "$myContents" "$SSBUpdateCheckVersion" 'Unable to check for a new version of Epichrome on Github.'
+	if [[ ! "$ok" ]] ; then
+	    alert "Warning: $errmsg" 'Checking For Update' '|caution'
+	    ok=1
+	else
+
+	    # if there's an update available, display a dialog
+	    if [[ "$updateResult" ]] ; then
+		# set separator to newline
+		oldifs="$IFS"
+		IFS=$'\n'
+
+		# convert result into an array
+		updateResult=( $(echo "$updateResult") )
+
+		# display dialog
+		dialog doEpichromeUpdate \
+		   "A new version of Epichrome (${updateResult[0]}) is available on GitHub." \
+		   "Update Available" \
+		   "|caution" \
+		   "+Download" \
+		   "-Later" \
+		   "Ignore This Version"
+		
+		# act based on dialog
+		if [[ "$ok" ]] ; then
+		    
+		    case "$doEpichromeUpdate" in
+			Download)
+			    # open the update URL
+			    open "${updateResult[1]}"
+			    ;;
+			
+			Later)
+			    # do nothing
+			    doEpichromeUpdate=
+			    ;;
+			*)
+			    # pretend we're already at the new version
+			    SSBUpdateCheckVersion="${updateResult[0]}"
+			    ;;
+		    esac
+		fi
+		
+		# alert the user to any error, but don't abort
+		if [[ ! "$ok" ]] ; then
+		    alert "Warning: $errmsg" 'Checking For Update' '|caution'
+		    ok=1
+		fi
+		
+		IFS="$oldifs"
+	    fi
 	fi
     fi
 fi
